version: '2'

services:

  postgres-95:
    image: postgres:9.5
    environment:
      POSTGRES_USER: sequelize_slugify_test
      POSTGRES_PASSWORD: sequelize_slugify_test
      POSTGRES_DB: sequelize_slugify_test
    ports:
      - "8195:5432"
    container_name: postgres-95

  mysql-57:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sequelize_slugify_test
      MYSQL_USER: sequelize_slugify_test
      MYSQL_PASSWORD: sequelize_slugify_test
    ports:
      - "8257:3306"
    container_name: mysql-57

  mariadb-103:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sequelize_slugify_test
      MYSQL_USER: sequelize_slugify_test
      MYSQL_PASSWORD: sequelize_slugify_test
    ports:
      - "8313:3306"
    container_name: mariadb-103

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Sequelize!!Slugify
    ports:
      - "8400:1433"
    container_name: mssql
